_target_: skill_generator.models.decoders.deterministic_decoder.DeterministicDecoder
act_dim: ${datamodule.action_space}
latent_dim: ${model.skill_dim}
layer_size: 256
num_layers: 2
criterion: HuberLoss #MSELoss
rnn_model: rnn_decoder
policy_rnn_dropout_p: 0.0