_target_: hulc.models.plan_encoders.plan_recognition_net.PlanRecognitionBiRNNNetwork
in_features: ???
plan_features: 256
action_space: ${datamodule.action_space}
birnn_dropout_p: 0.0
rnn_type: nn.RNN  # nn.GRU
