_target_: hulc.models.perceptual_encoders.concat_encoders.ConcatEncoders
_recursive_: false

defaults:
 - rgb_static: default
 - rgb_gripper: default
 - depth_static: none
 - depth_gripper: none
 - proprio: none
 - tactile: none
