_target_: pytorch_lightning.callbacks.ModelCheckpoint
save_top_k: 3
monitor: val/total_loss
verbose: True
mode: min
dirpath: saved_models
filename: '{epoch}' #put back in when PL fixes this _{val/accuracy:.4f}'
