_target_: hulc.datasets.shm_dataset.ShmDataset
key: "vis"
save_format: "npz"
batch_size: 32
min_window_size: 20
max_window_size: 32
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
pad: true
lang_folder: "lang_annotations"
num_workers: 2
