_target_: skill_generator.models.decoders.logistic_decoder.LogisticDecoder
act_dim: ${datamodule.action_space}
latent_dim: ${model.skill_dim}
layer_size: 128
num_layers: 2
n_dist: 3
criterion: HuberLoss #MSELoss
rnn_model: lstm_decoder
policy_rnn_dropout_p: 0.0