_target_: skill_generator.models.decoders.lstm_action_decoder.LSTMActionDecoder
act_dim: ${datamodule.action_space}
latent_dim: ${model.skill_dim}
layer_size: 128
num_layers: 2
criterion: MSELoss
gripper_control: True