defaults:
  - /callbacks/rollout/tasks@tasks: new_playtable_tasks
  - /annotations@val_annotations: new_playtable_validation
_target_: hulc.rollout.rollout_long_horizon.RolloutLongHorizon
_recursive_: false
env_cfg:
  _target_: hulc.wrappers.hulc_wrapper.HulcWrapper
skip_epochs: 1
rollout_freq: 2
num_videos: 8
num_sequences: 512
replan_freq: 30
ep_len: 360
empty_cache: false
log_video_to_file: false
save_dir: ./videos
lang_folder: ${datamodule.datasets.lang_dataset.lang_folder}
debug: false
