_target_: skill_generator.models.skill_generator.SkillGenerator
defaults:
  - action_encoder: default
  - action_decoder: deterministic
  - prior_locator: prior_locator
  - optimizer: adam
  - lr_scheduler: constant
_recursive_: false

skill_dim: 10
skill_len: ${datamodule.datasets.window_size}
kl_beta: ${loss.kl_beta}
kl_sigma: ${loss.kl_sigma}
prior_seeking_mode: 2
scale: [0.8, 0.94, 2.0]