_target_: skill_generator.models.skill_generator.SkillGenerator
defaults:
  - action_encoder: default
  - action_decoder: deterministic
  - prior_locator: prior_locator
  - optimizer: adam
  - lr_scheduler: constant
_recursive_: false

skill_dim: 15
min_skill_len: 2
max_skill_len: 5
kl_beta: ${loss.kl_beta}
kl_sigma: ${loss.kl_sigma}
prior_seeking_balance: 0.8
magic_scale: [1.4, 3.5, 0.75]
prior_locator_weight: [0.16, 0.48, 0.36]